
colorScheme = "blowfish"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = false
replyByEmail = false
mainSections = ["section1", "section2"]
disableImageOptimization = false
disableTextInHeader = false
# giteaDefaultServer = "https://git.fsfe.org"
# forgejoDefaultServer = "https://v8.next.forgejo.org"

[header]
  layout = "basic" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "custom" # valid options: page, profile, hero, card, background, custom
  showRecent = true
  showRecentItems = 6
  #homepageImage = "IMAGE.jpg" # used in: hero, and card
  # layoutBackgroundBlur = false # only used when layout equals background
  cardViewScreenWidth = true
  cardView = true
  showMoreLink = true
  showMoreLinkDest = "/posts"

[article]
  showDate = true
  # showViews = true
  # showLikes = false
  # showDateOnlyInArticle = false
  # showDateUpdated = false
  showAuthor = false
  # # showAuthorBottom = false
  showHero = false  # большая картинка в начале поста
  # # heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  # layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  # layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  # showBreadcrumbs = false
  showDraftLabel = true
  # showEdit = false
  # # editURL = "https://github.com/username/repo/"
  # editAppendPath = true
  # seriesOpened = false
  # showHeadingAnchors = true
  # showPagination = true
  # invertPagination = false
  # showReadingTime = true
  showTableOfContents = true
  # # showRelatedContent = false
  # # relatedContentLimit = 3
  showTaxonomies = true  # включает тэги
  # showAuthorsBadges = false
  # showWordCount = true
  # # sharingLinks = [ "linkedin", "twitter", "bluesky", "mastodon", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram"]
  # showZenMode = false

[list]
  # showHero = false
  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  # layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  # layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  # showBreadcrumbs = false
  showSummary = true
  # showViews = false
  # showLikes = false
  # showTableOfContents = false
  showCards = true
  # orderByWeight = false
  # groupByYear = true
  cardView = true
  # cardViewScreenWidth = false
  # constrainItemsWidth = false

[sitemap]
  # excludedKinds = ["taxonomy", "term"]

[taxonomy]
  # showTermCount = true
  # showHero = false
  # # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  # showBreadcrumbs = false
  # showViews = false
  # showLikes = false
  # showTableOfContents = false
  # cardView = false

[term]
  # showHero = false
  # # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  # showBreadcrumbs = false
  # showViews = false
  # showLikes = false
  # showTableOfContents = true
  # groupByYear = false
  # cardView = false
  # cardViewScreenWidth = false

[firebase]
  # apiKey = "XXXXXX"
  # authDomain = "XXXXXX"
  # projectId = "XXXXXX"
  # storageBucket = "XXXXXX"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  # measurementId = "XXXXXX"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[umamiAnalytics]
  # websiteid = "ABC12345"
  # domain = "llama.yoursite.com"
  # dataDomains = "yoursite.com,yoursite2.com"
  # scriptName = ""
  # enableTrackEvent = true

[selineAnalytics]
  # token = "XXXXXX"
  # enableTrackEvent = true

[buymeacoffee]
  # identifier = ""
  # globalWidget = true
  # globalWidgetMessage = "Hello"
  # globalWidgetColor = "#FFDD00"
  # globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
  # fediverse = ""

[rssnext]
  # feedId = ""
  # userId = ""
